---
version: '3'
services:

  homeassistant:
    container_name: home-assistant
    image: {{ homeassistant_image }}
    volumes:
      - {{ homeassistant_config_volume }}
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB-ConbeeII:/dev/ttyUSB-ConbeeII
    environment:
      - TZ={{ host_timezone }}
    restart: unless-stopped
    priveleged: true
    network_mode: host

  eclipse-mosquitto:
    container_name: mosquitto
    image: {{ mosquitto_image }}
    volumes:
      - {{ mosquitto_config_volume }}
    environment:
      - TZ={{ host_timezone }}
    restart: always
    network_mode: host
