---
version: '3'
services:

  homeassistant:
    container_name: home-assistant
    image: {{ homeassistant_image }}
    volumes:
      - {{ homeassistant_config_volume }}
    environment:
      - TZ={{ host_timezone }}
    restart: always
    network_mode: host

  eclipse-mosquitto:
    container_name: mosquitto
    image: {{ mosquitto_image }}
    volumes:
      - {{ mosquitto_config_volume }}
    environment:
      - TZ={{ host_timezone }}
    restart: always
    network_mode: host

  deconz:
    container_name: deconz
    image: {{ deconz_image }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{ deconz_config_dir }}:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - {{ deconz_device }}:{{ deconz_device }}
    environment:
      - TZ={{ host_timezone }}
      - DECONZ_DEVICE={{ deconz_device }}
    restart: always
    network_mode: host
